### PR TITLE
Webitools-175: Integrates architecture studio cli command

### PR DESCRIPTION
**Pull request by CAST-ANJ**

### CODE REVIEW

**Comment by leon2Meudon92** [comment]
- Missing integration tests
- Should have a jenkins job running the architecture studio test. Add your new job in this view https://jenkins15.corp.castsoftware.com/view/AipConsole/view/AipConsoleTools_V2_TestIntegr/
- Missing JENKINS plugin architecture studio command part

**Comment by leon2Meudon92** [comment]
I didn't see md updated for jenkins plugin (online documentation I means)

**Comment by CAST-ANJ** [comment]
Added the doc for Jenkins plugin. It can be tested and merged.

**Comment by leon2Meudon92** [comment]
Two things left to be done before merging
- Please update log messages: no clear text message (should be from properties)
- The name of All related build steps should start with Cast Console (same as the existing I mean)

**Pull request merged**
