### PR TITLE
IMAGKSL-1279 fix publish to engineering dashboard option not working

### PR DESCRIPTION
**Pull request by SufyaanKhateeb**
Fix the 'Deep-Analyze' to publish to dashboard when the option --publish-engineering is true.

### CODE REVIEW

**Comment by leon2Meudon92** [comment]
Missing unit tests

1. Install CAST Imaging on a VM or your laptop
2. From here https://jenkins15.corp.castsoftware.com/view/AipConsole/view/AipConsole%20Tools/
3. update all tests jobs starting with AipConsoleTools_V3_TestIntegr_DeepAnalysis/
4. target URL is what you installed on step 1

**Comment by leon2Meudon92** [comment]
Your changes is only related to CLI.
Please update the same for JENKINS plugin in the project

**Comment by SufyaanKhateeb** [comment]
> Missing unit tests
> 
> 1. Install CAST Imaging on a VM or your laptop
> 2. From here https://jenkins15.corp.castsoftware.com/view/AipConsole/view/AipConsole%20Tools/
> 3. update all tests jobs starting with AipConsoleTools_V3_TestIntegr_DeepAnalysis/
> 4. target URL is what you installed on step 1

None of the integration tests are broken. Do you mean I have to create new tests?

**Comment by leon2Meudon92** [comment]
I mean you should update the existing to have the parameters that you added working as expected.
Also you should have jenkins jobs for FastScan, DeepAnalyze and Onboard application using your new parameters

**Comment by SufyaanKhateeb** [comment]
Closing this PR as the issue has already been resolved in [PR](https://github.com/CAST-Extend/com.castsoftware.aip.console.tools/pull/204)

**Pull request closed without merging**
