### PR TITLE
WEBITOOLS-186:Adds upgrade and resync application command

### PR DESCRIPTION
**Pull request by CAST-ANJ**
@leon2Meudon92 Please review and merge

### CODE REVIEW

**Comment by leon2Meudon92** [comment]
- I didn't find tests classes
- Use application name, version name etc instead of their related GUID. For user it's easier to provide the name

**Comment by CAST-ANJ** [comment]
Added test cases

**Comment by CAST-ANJ** [comment]
Added all the changes required to change app guid to app name. 
Need to test everything again.

**Comment by CAST-ANJ** [comment]
Testing completed can be merged if everything seems fine to you @leon2Meudon92

**Pull request merged**
